### ISSUE TITLE
Cannot run with Orthanc 1.5.0

### ISSUE THREAD

**Issue by Betalos** [Doc-Cirrus/orthanc-mongodb#15]
When i try to run i get this issue:
`./Orthanc --config Configuration.json 
W1212 18:16:05.691010 main.cpp:1272] Option unsupported by the core of Orthanc: --config
W1212 18:16:05.691149 main.cpp:1298] Orthanc version: 1.3.2
W1212 18:16:05.693793 OrthancInitialization.cpp:120] Reading the configuration from: "Configuration.json"
W1212 18:16:05.694853 Toolbox.cpp:1358] Falling back to system-wide default locale
W1212 18:16:05.712647 FromDcmtkBridge.cpp:164] Loading the external DICOM dictionary "/usr/share/libdcmtk8/dicom.dic"
W1212 18:16:05.727631 FromDcmtkBridge.cpp:164] Loading the external DICOM dictionary "/usr/share/libdcmtk8/private.dic"
W1212 18:16:05.750983 main.cpp:671] Loading plugin(s) from: /opt/ft/ft-pacs/web-dicom/libOrthancDicomWeb.so
W1212 18:16:05.765231 PluginsManager.cpp:269] Registering plugin 'dicom-web' (version 0.5)
W1212 18:16:05.765579 PluginsManager.cpp:168] URI to the DICOMweb REST API: /dicom-web/
W1212 18:16:05.765894 PluginsManager.cpp:168] URI to the WADO-URI API: /wado
W1212 18:16:05.765917 main.cpp:671] Loading plugin(s) from: /opt/ft/ft-pacs/db-plugin/orthanc-mongodb-build/libOrthancMongoDBIndex.so
W1212 18:16:05.777400 PluginsManager.cpp:269] Registering plugin 'MongoDBIndex' (version 1.0.0)
W1212 18:16:05.777625 PluginsManager.cpp:168] Using MongoDB index
W1212 18:16:05.782761 main.cpp:671] Loading plugin(s) from: /opt/ft/ft-pacs/db-plugin/orthanc-mongodb-build/libOrthancMongoDBStorage.so
W1212 18:16:05.783457 PluginsManager.cpp:219] Unregistering plugin 'MongoDBIndex' (version 1.0.0)
W1212 18:16:05.783489 PluginsManager.cpp:168] MongoDB index is finalizing
W1212 18:16:05.784010 PluginsManager.cpp:219] Unregistering plugin 'dicom-web' (version 0.5)
E1212 18:16:05.788076 main.cpp:1341] Uncaught exception, stopping now: [cannot create a mongocxx::instance object if one has already been created]`

**Comment by ihor-mozil** [comment]
Fix merged. Please verify.

**Comment by Betalos** [comment]
I confirm it's working now with the last commit.
