### ISSUE TITLE
Address Orthanc@1.9.2 DB plugin refactoring

### ISSUE THREAD

**Issue by Betalos** [Doc-Cirrus/orthanc-mongodb#33]
Hello everyone.
Well as you know orthanc has just released somewhat major db refactoring release,:

**Starting with Orthanc 1.9.2 and PostgreSQL plugins 4.0, Orthanc will be compatible with multiple writers/readers sharing the same database. One Orthanc server will also manage several connections to PostgreSQL, in order to improve performance by adding concurrency.
Orthanc was originally designed as a mini-DICOM server in 1-to-1 relation with a SQLite database. Supporting multiple writers/readers necessitated a full refactoring of the database engine, so as to be able to replay transactions in the case of collisions. This refactoring should enable hospital-wide VNA scenarios.**

So could we discuss how we can move the plugin forward with this release.
Also I still have a pending pull request I would be glad if could merge it (so every one benefit from the performance boost)

**Comment by Betalos** [comment]
Hello there.
I update the plugin file structure (inspired by orthanc-database one), and now the plugin support the new orthanc@1.9.2+ SDK.
This is Still a WIP (need to update the README section for the build) but you can give it a try.
[Here is my fork repo.](https://github.com/Betalos/orthanc-mongodb)

**Comment by phtran-dev** [comment]
Hi @Betalos ,
Can you please give instructions to  compile your repo ? This is my cmake command
cmake .. -DCMAKE_BUILD_TYPE=Release -DSTANDALONE_BUILD=ON -DSTATIC_BUILD=ON -DALLOW_DOWNLOADS=ON

But it throws error:
  Cannot find source file:

    /tmp/orthanc-mongodb/Framework/SQLite/SQLiteDatabase.cpp

**Comment by phtran-dev** [comment]
HI @Betalos ,
What version of mongocxx are you using ? I am using version 3.4.2 seems like your code is not compatible with that version at these lines in MongoDB/Plugins/MongoDBIndex.cpp

 971         if (hasServer) {
 972             query.reset(make_document(kvp("property", property), kvp("server", serverIdentifier)));
 973             pDocument.reset(
 974                     make_document(kvp("property", property), kvp("value", utf8), kvp("server", serverIdentifier))
 975             );
 976         }

**Comment by Betalos** [comment]
Hello @phtran-dev ,

Well you should use the latest version of mongoc and mongocxx. I didn't had time to finish the building process, but basically you need to build and install mongoc and mongocxx.

**Comment by phtran-dev** [comment]
Thanks @Betalos ,
I am using the latest version of mongoCxx and mongoc
What command are you using to compile your plugin ? I am using this 
cmake ../MongoDB/ -DCMAKE_BUILD_TYPE=Release -DSTANDALONE_BUILD=ON -DUSE_SYSTEM_ORTHANC_SDK=OFF -DORTHANC_SDK_VERSION=1.9.2 -DALLOW_DOWNLOADS=ON

make

But cmake cannot find the "mongocxx/cursor.hpp" 

MongoDB/Plugins/MongoDBIndex.h:24:10: fatal error: mongocxx/cursor.hpp: No such file or directory
   24 | #include <mongocxx/cursor.hpp>

I tried a simple cmake like below
cmake_minimum_required(VERSION 3.16)
project(mongo_test)

#set(CMAKE_CXX_STANDARD 17)

add_executable(mongo_test main.cpp)

find_package(mongocxx REQUIRED)
find_package(bsoncxx REQUIRED)
#include_directories(${LIBMONGOCXX_INCLUDE_DIR})
#include_directories(${LIBBSONCXX_INCLUDE_DIR})

target_link_libraries(${PROJECT_NAME} PRIVATE mongo::bsoncxx_shared)

target_link_libraries(${PROJECT_NAME} PRIVATE mongo::mongocxx_shared)

And this is main.cpp
   cat ../main.cpp 
#include <iostream>
#include <mongocxx/cursor.hpp>
#include <mongocxx/client.hpp>

int main() 
{
  return 1;
}

It can compile, so I can be sure that mongocxx is installed on my machine correctly. But I have no idea why your plugin cmake cannot find the mongocxx/cursor.hpp and mongocxx/client.hpp . Can you give me your advice ? What is your command to compile your plugin ?

**Comment by phtran-dev** [comment]
Thanks @Betalos ,

I manged to compiled the plugin. However when I test those dicoms (find in the attachment), I see that the plugin generates 3 studies instead of one (which SQLite
[test_dicom.zip](https://github.com/Doc-Cirrus/orthanc-mongodb/files/7578133/test_dicom.zip)
 Plugin generates). Can you please help to verify and test ?

**Comment by Betalos** [comment]
Hello @phtran-dev.

That's a weird issue, could you tell me how you did the upload of these instances into the pacs.
Also is the studies are identical (check the orthanc's rest api for the studyUID if it's the same)

**Comment by phtran-dev** [comment]
Hi @Betalos ,
I uploaded dicom instances via orthanc GUI. Yes the studies are identical since  studyInstanceUID, PID of those dicom instances are the same.

**Comment by phtran-dev** [comment]
It's weird that sometimes it creates 3, sometimes it creates only 1. Not sure if there is missing database locking in the plugin'code ?

**Comment by Betalos** [comment]
hello @phtran-dev.

Well this issue is with http client (posting the dcm vi http), if you used [dcmsend](https://support.dcmtk.org/docs/dcmsend.html) (which emulate dicom c-store scu) it will work.
I didn't have the time to test it with postgress plugin to see if it related to orthanc or the plugin.
well the plugin have db locking,  here the issue has to do with http multi threads somehow.

**Comment by phtran-dev** [comment]
Thanks @Betalos ,
From your experience, do you think this mongo plugin can handle hundreds of millions of dicom instance (or even billion of instances)?

**Comment by Betalos** [comment]
hello @phtran-dev, sorry for taking too much time to replay.
To answer your question, we have some systems in production with 2to of data, and the system is stable and the requests not very slow.
but this version of the plugin still have some issues with locking mechanism. when we deployed it to prod, it had some performance degradation. So I need to look it up.
