### ISSUE TITLE
Jsoncpp is searched for in the system paths, not in CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by espakm** [Doc-Cirrus/orthanc-mongodb#5]
The build instructions tell to build jsoncpp manually. However, if jsoncpp is not installed in the default location (/usr/local), it won't be found when configuring the mongodb plugin, even if you set CMAKE_PREFIX_PATH.

This commit fixes that:

  - https://github.com/espakm/orthanc-mongodb/commit/4b27812d0b8e643b5235abc075edfbc3c2a1a87a

**Comment by kosch** [comment]
Can you create Pull Requests for your changes? That would be nice.

**Comment by espakm** [comment]
Separate PR-s sent for all my changes.

**Comment by kosch** [comment]
Thank you very much!

**Comment by espakm** [comment]
Welcome. Thanks for merging so quickly! :+1:
